### ISSUE TITLE
svg2png 0.2.0 doesn't work for me (hangs)

### ISSUE THREAD

**Issue by flokli** [dbushell/grunt-svg2png#1]
I tried version 0.2.0, using config:

``` javascript
            svg2png: {
                all: {
                    files: [{
                            src: ['main/icons-src/common/*.svg'],
                            dest: 'main/icons/common/'
                        }
                    ]
                }
            },
```

Output:

``` console
Running "svg2png:all" (svg2png) task

Rasterizing SVG to PNG (25 files)...
0% [ =                         ] 4.00% (0.2s) ^C
Shutting down the watch task...OK
```

... it keept staying at the 4.00%, until I killed it manually.

With Version 0.1.2 and the same config, it works without any problems after a second.

Is this a known problem? Should I provide any more information for you to debug?

**Comment by esr360** [comment]
Does anyone know what was causing this issue? It sounds like an exact problem I'm having.
